FROM google/cloud-sdk:latest

# Install Essentials
# RUN yum update -y && \
#     yum clean all

RUN apt-get update
RUN apt-get upgrade -y

# Install Packages
RUN apt update && apt install git && \
    wget && \
    java-1.8.0-openjdk && \
    sudo && \
    apt-get clean

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000

ENV JENKINS_HOME /home/${user}  

# Jenkins is run with user `jenkins`, uid = 1000
RUN groupadd -g ${gid} ${group} \
    && useradd -d "$JENKINS_HOME" -u ${uid} -g ${gid} -m -s /bin/bash ${user}

RUN chown -R ${user}:${user} /home/${user}

# Add the jenkins user to sudoers
RUN echo "${user}    ALL=(ALL)    ALL" >> etc/sudoers
